### PR TITLE
added glfw hints for 4.5 context - fixed incompatibility with Mesa

### PR DESCRIPTION
**Pull request by 0xBAMA**
Also, just so you know there's no linux makefile for project number 41 - thanks again for making this available.

-Jon

### CODE REVIEW

**Comment by capnramses** [comment]
---comments pasted in from external message---
/paste
cool. i think we can probably change it to remove the apple part entirely and just default to 4.1 everywhere. does 4.1 work for your mesa (except for compute shaders of course)?

to answer earlier q: yeah systems without 4.5 support but with 4.1 will most likely fail to start a context. so i try to use the minimum version i can get away with
the version request system for contexts is very bad
did the compute shaders with 4.3 hint work on mesa ?
/endpaste

**Comment by capnramses** [comment]
this is my comment from the first tutorial http://antongerdelan.net/opengl/hellotriangle.html

> 
> This bit is out of date:
> 
> // uncomment these lines if on Apple OS X
> /*glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
> glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 2);
> glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE);
> glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);*/
> 
> I suggest everyone uncomment this and start with trying 4.1 on all systems, which should now also work correctly on OS X:
> 
> glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 4);
> glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 1);
> glfwWindowHint(GLFW_OPENGL_FORWARD_COMPAT, GL_TRUE);
> glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);

**Comment by 0xBAMA** [comment]
Yes, 4.3 worked for the compute shader example. The Mesa implementation supports 4.5, on my 2013 Haswell laptop - I didn't know about the version handling, probably best to do 4.1 if it's a question.

**Comment by capnramses** [comment]
looks good to me! thanks for all that

**Pull request merged**
